export const MovieData = [
  // {
  //   adult: false,
  //   backdrop_path: "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
  //   genre_ids: (3)[(878, 28, 12)],
  //   id: 912649,
  //   original_language: "en",
  //   original_title: "Venom: The Last Dance",
  //   overview:
  //     "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
  //   popularity: 7523.862,
  //   poster_path: "/k42Owka8v91trK1qMYwCQCNwJKr.jpg",
  //   release_date: "2024-10-22",
  //   title: "Venom: The Last Dance",
  //   video: false,
  //   vote_average: 6.5,
  //   vote_count: 225,
  // },
  {
    adult: false,
    backdrop_path: "/v9acaWVVFdZT5yAU7J2QjwfhXyD.jpg",
    genre_ids: (3)[(16, 878, 10751)],
    id: 1184918,
    original_language: "en",
    original_title: "The Wild Robot",
    overview:
      "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    popularity: 8387.193,
    poster_path: "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
    release_date: "2024-09-12",
    title: "The Wild Robot",
    video: false,
    vote_average: 8.604,
    vote_count: 1805,
  },
  {
    adult: false,
    backdrop_path: "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
    genre_ids: (2)[(27, 53)],
    id: 1034541,
    original_language: "en",
    original_title: "Terrifier 3",
    overview:
      "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
    popularity: 4830.304,
    poster_path: "/63xYQj1BwRFielxsBDXvHIJyXVm.jpg",
    release_date: "2024-10-09",
    title: "Terrifier 3",
    video: false,
    vote_average: 7.3,
    vote_count: 254,
  },
  {
    adult: false,
    backdrop_path: "/9oYdz5gDoIl8h67e3ccv3OHtmm2.jpg",
    genre_ids: (3)[(27, 878, 53)],
    id: 933260,
    original_language: "en",
    original_title: "The Substance",
    overview:
      "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
    popularity: 3173.39,
    poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
    release_date: "2024-09-07",
    title: "The Substance",
    video: false,
    vote_average: 7.3,
    vote_count: 965,
  },
  {
    adult: false,
    backdrop_path: "/4KHEK6AQFHhv4TDtL3KLReePB05.jpg",
    genre_ids: (3)[(28, 27, 53)],
    id: 1029235,
    original_language: "en",
    original_title: "Azrael",
    overview:
      "In a world where no one speaks, a devout female hunts down a young woman who has escaped her imprisonment. Recaptured by its ruthless leaders, Azrael is due to be sacrificed to pacify an ancient evil deep within the surrounding wilderness.",
    popularity: 1469.42,
    poster_path: "/qpdFKDvJS7oLKTcBLXOaMwUESbs.jpg",
    release_date: "2024-09-27",
    title: "Azrael",
    video: false,
    vote_average: 6.1,
    vote_count: 97,
  },
  {
    adult: false,
    backdrop_path: "/hd1TvTUGjkoYoqvXYfSBpI5Ri9B.jpg",
    genre_ids: (4)[(16, 28, 12, 878)],
    id: 1159311,
    original_language: "ja",
    original_title: "僕のヒーローアカデミア THE MOVIE ユアネクスト",
    overview:
      "In a society devastated by the effects of an all-out war between heroes and villains, a mysterious giant fortress suddenly appears, engulfing towns and people one after another. Then, a man reminiscent of All Might, the 'symbol of peace', stands in front of Izuku and his friends...",
    popularity: 1133.644,
    poster_path: "/8rdB1wkheEMMqcY8qLAKjCMPcnZ.jpg",
    release_date: "2024-08-02",
    title: "My Hero Academia: You're Next",
    video: false,
    vote_average: 6.983,
    vote_count: 29,
  },
  {
    adult: false,
    backdrop_path: "/of1tQasFGCeHgWPmSgdA1WS6hNW.jpg",
    genre_ids: (3)[(80, 53, 28)],
    id: 1047373,
    original_language: "en",
    original_title: "The Silent Hour",
    overview:
      "While working a case as an interpreter, a hearing-impaired police detective must confront a group of criminals trying to eliminate a deaf murder witness in her apartment building.",
    popularity: 852.747,
    poster_path: "/j736cRzBtEPCm0nHnpRN1prqiqj.jpg",
    release_date: "2024-10-03",
    title: "The Silent Hour",
    video: false,
    vote_average: 6.3,
    vote_count: 41,
  },
  {
    adult: false,
    backdrop_path: "/cVg97LOJgrDZJ7bVmjU2KsGRYnU.jpg",
    genre_ids: (2)[(27, 9648)],
    id: 1100782,
    original_language: "en",
    original_title: "Smile 2",
    overview:
      "About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, Skye is forced to face her dark past to regain control of her life before it spirals out of control.",
    popularity: 766.404,
    poster_path: "/aE85MnPIsSoSs3978Noo16BRsKN.jpg",
    release_date: "2024-10-16",
    title: "Smile 2",
    video: false,
    vote_average: 7,
    vote_count: 196,
  },
  {
    adult: false,
    backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
    genre_ids: (3)[(16, 14, 12)],
    id: 823219,
    original_language: "xx",
    original_title: "Flow",
    overview:
      "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
    popularity: 710.19,
    poster_path: "/dzDMewC0Hwv01SROiWgKOi4iOc1.jpg",
    release_date: "2024-08-30",
    title: "Flow",
    video: false,
    vote_average: 8.9,
    vote_count: 128,
  },
  {
    adult: false,
    backdrop_path: "/mpMDztY5OmV7i4ypYpWgqsP4DHs.jpg",
    genre_ids: (2)[(27, 53)],
    id: 978796,
    original_language: "en",
    original_title: "Bagman",
    overview:
      "For centuries and across cultures, parents have warned their children of the legendary Bagman, who snatches innocent children and stuffs them into his vile, rotting bag—never to be seen again. Patrick McKee narrowly escaped such an encounter as a boy, which left him with lasting scars throughout his adulthood. Now, Patrick’s childhood tormentor has returned, threatening the safety of his wife Karina and son Jake.",
    popularity: 758.936,
    poster_path: "/pkKcIP2B2ILAh4lGKyn9YkO0L1t.jpg",
    release_date: "2024-09-20",
    title: "Bagman",
    video: false,
    vote_average: 6.476,
    vote_count: 42,
  },
  {
    adult: false,
    backdrop_path: "/yjPXIgY3QoHe8Kt8nEJCz97UF3q.jpg",
    genre_ids: (3)[(18, 36, 10752)],
    id: 832964,
    original_language: "en",
    original_title: "Lee",
    overview:
      "The true story of photographer Elizabeth 'Lee' Miller, a fashion model who became an acclaimed war correspondent for Vogue magazine during World War II.",
    popularity: 495.175,
    poster_path: "/zdNWyuim8gpJHe1LtKaDrs43dWz.jpg",
    release_date: "2024-09-12",
    title: "Lee",
    video: false,
    vote_average: 6.805,
    vote_count: 110,
  },
  {
    adult: false,
    backdrop_path: "/l8OyAXEp5FKZWmDhqJMbiwAEvz.jpg",
    genre_ids: (2)[(27, 18)],
    id: 814889,
    original_language: "en",
    original_title: "Never Let Go",
    overview:
      "As an evil takes over the world beyond their front doorstep, the only protection for a mother and her twin sons is their house and their family’s protective bond.",
    popularity: 551.087,
    poster_path: "/3EpZ2ksjijmdr8BhISP03PYzNFW.jpg",
    release_date: "2024-09-18",
    title: "Never Let Go",
    video: false,
    vote_average: 6.201,
    vote_count: 153,
  },
  {
    adult: false,
    backdrop_path: "/fNylhsI3u6NmTxeanFPDEwvT9GS.jpg",
    genre_ids: (3)[(80, 18, 53)],
    id: 835113,
    original_language: "en",
    original_title: "Woman of the Hour",
    overview:
      "An aspiring actress crosses paths with a prolific serial killer in '70s LA when they're cast on an episode of \"The Dating Game.\"",
    popularity: 456.339,
    poster_path: "/nc9ZqrJFbcUdlMg9lxXXtJb24jU.jpg",
    release_date: "2024-10-03",
    title: "Woman of the Hour",
    video: false,
    vote_average: 6.7,
    vote_count: 250,
  },
  {
    adult: false,
    backdrop_path: "/co7oxvpWxgd6FZU24DnljDDHYQA.jpg",
    genre_ids: (3)[(878, 53, 27)],
    id: 1064028,
    original_language: "en",
    original_title: "Subservience",
    overview:
      "With his wife out sick, a struggling father brings home a lifelike AI, only to have his self-aware new help want everything her new family has to offer... Like the affection of her owner and she'll kill to get it.",
    popularity: 388,
    poster_path: "/gBenxR01Uy0Ev9RTIw6dVBPoyQU.jpg",
    release_date: "2024-08-15",
    title: "Subservience",
    video: false,
    vote_average: 6.8,
    vote_count: 207,
  },
  {
    adult: false,
    backdrop_path: "/bizhlTVjifYQUu4Xrdt7m3TYr7d.jpg",
    genre_ids: (2)[(27, 53)],
    id: 1226578,
    original_language: "en",
    original_title: "Longlegs",
    overview:
      "FBI Agent Lee Harker is assigned to an unsolved serial killer case that takes an unexpected turn, revealing evidence of the occult. Harker discovers a personal connection to the killer and must stop him before he strikes again.",
    popularity: 310.419,
    poster_path: "/5aj8vVGFwGVbQQs26ywhg4Zxk2L.jpg",
    release_date: "2024-05-31",
    title: "Longlegs",
    video: false,
    vote_average: 6.7,
    vote_count: 1137,
  },
  {
    adult: false,
    backdrop_path: "/iURqo6oIwbeegIwWXx5qrBsDcPk.jpg",
    genre_ids: (4)[(10751, 12, 14, 35)],
    id: 826510,
    original_language: "en",
    original_title: "Harold and the Purple Crayon",
    overview:
      "Inside of his book, adventurous Harold can make anything come to life simply by drawing it. After he grows up and draws himself off the book's pages and into the physical world, Harold finds he has a lot to learn about real life.",
    popularity: 285.342,
    poster_path: "/qtW6bWUEqfPLaD6KnetIlSG4adf.jpg",
    release_date: "2024-07-31",
    title: "Harold and the Purple Crayon",
    video: false,
    vote_average: 7,
    vote_count: 163,
  },
  {
    adult: false,
    backdrop_path: "/z8muwOfNZ4qivqgASnIkeeHSSX3.jpg",
    genre_ids: [27],
    id: 1089123,
    original_language: "en",
    original_title: "Daddy's Head",
    overview:
      "A boy and his stepmother fear for their safety after an eerie creature resembling the boy's recently deceased father visits them.",
    popularity: 295.403,
    poster_path: "/nEWbEBs8BalwasA4Un8rll3kauT.jpg",
    release_date: "2024-10-10",
    title: "Daddy's Head",
    video: false,
    vote_average: 5.662,
    vote_count: 34,
  },
  {
    adult: false,
    backdrop_path: "/e0xnvkG0nZjEfvREuhgFekJZmQr.jpg",
    genre_ids: (2)[(28, 12)],
    id: 558449,
    original_language: "en",
    original_title: "Gladiator II",
    overview:
      "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
    popularity: 240.991,
    poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    release_date: "2024-11-13",
    title: "Gladiator II",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/tPfXJcXxQ3MHyvhzNsDgsXoyPEM.jpg",
    genre_ids: (2)[(27, 9648)],
    id: 1249532,
    original_language: "en",
    original_title: "Rippy",
    overview:
      "Young police officer Maddy is determined to live up to her deceased father's legacy. Her courage is put to the test when locals are found brutally ripped to shreds by the zombie kangaroo. As the undead beast leaves a trail of carnage, Maddy, with the help of her eccentric Uncle Schmitty and resilient Aunt Donna, must embark on a high-stakes battle to save the town.",
    popularity: 323.379,
    poster_path: "/cZ5U4Ae74g29E02JR5oR98RQhiR.jpg",
    release_date: "2024-10-25",
    title: "Rippy",
    video: false,
    vote_average: 3.222,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: "/rOmUuQEZfPXglwFs5ELLLUDKodL.jpg",
    genre_ids: (3)[(35, 28, 14)],
    id: 845781,
    original_language: "en",
    original_title: "Red One",
    overview:
      "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous bounty hunter in a globe-trotting, action-packed mission to save Christmas.",
    popularity: 229.147,
    poster_path: "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg",
    release_date: "2024-10-31",
    title: "Red One",
    video: false,
    vote_average: 6.5,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
    genre_ids: (3)[(878, 28, 12)],
    id: 912649,
    original_language: "en",
    original_title: "Venom: The Last Dance",
    overview:
      "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
    popularity: 7523.862,
    poster_path: "/k42Owka8v91trK1qMYwCQCNwJKr.jpg",
    release_date: "2024-10-22",
    title: "Venom: The Last Dance",
    video: false,
    vote_average: 6.538,
    vote_count: 235,
  },
  {
    adult: false,
    backdrop_path: "/2K2iXKB5sDJ0V3Q6U6VBmuzCPXl.jpg",
    genre_ids: (2)[(27, 53)],
    id: 1063877,
    media_type: "movie",
    original_language: "en",
    original_title: "Don't Move",
    overview:
      "A grieving woman in a secluded forest encounters a killer who injects her with a paralytic drug. As her body shuts down, her fight for survival begins.",
    popularity: 158.726,
    poster_path: "/cRDJxdnRb7ikKd6fVJTrGeaL34v.jpg",
    release_date: "2024-10-24",
    title: "Don't Move",
    video: false,
    vote_average: 6.7,
    vote_count: 185,
  },
  {
    adult: false,
    backdrop_path: "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
    genre_ids: (2)[(27, 53)],
    id: 1034541,
    media_type: "movie",
    original_language: "en",
    original_title: "Terrifier 3",
    overview:
      "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
    popularity: 4830.304,
    poster_path: "/63xYQj1BwRFielxsBDXvHIJyXVm.jpg",
    release_date: "2024-10-09",
    title: "Terrifier 3",
    video: false,
    vote_average: 7.3,
    vote_count: 257,
  },
  {
    adult: false,
    backdrop_path: "/begseNUKhZcc05Bc1UggaX5GeES.jpg",
    genre_ids: (3)[(28, 53, 80)],
    id: 976734,
    media_type: "movie",
    original_language: "en",
    original_title: "Canary Black",
    overview:
      "Top level CIA agent Avery Graves is blackmailed by terrorists into betraying her own country to save her kidnapped husband. Cut off from her team, she turns to her underworld contacts to survive and help locate the coveted intelligence that the kidnappers want.",
    popularity: 133.517,
    poster_path: "/hhiR6uUbTYYvKoACkdAIQPS5c6f.jpg",
    release_date: "2024-10-10",
    title: "Canary Black",
    video: false,
    vote_average: 6.5,
    vote_count: 105,
  },
  {
    adult: false,
    backdrop_path: "/fzkLKtZCkYSDzxoqntE5KgIqvzk.jpg",
    genre_ids: (6)[(12, 36, 28, 18, 10749, 53)],
    id: 1084736,
    media_type: "movie",
    original_language: "fr",
    original_title: "Le Comte de Monte-Cristo",
    overview:
      "Edmond Dantes becomes the target of a sinister plot and is arrested on his wedding day for a crime he did not commit. After 14 years in the island prison of Château d’If, he manages a daring escape. Now rich beyond his dreams, he assumes the identity of the Count of Monte-Cristo and exacts his revenge on the three men who betrayed him.",
    popularity: 253.897,
    poster_path: "/sAT1P3FGhtJ68anUyJScnMu8t1l.jpg",
    release_date: "2024-06-28",
    title: "The Count of Monte-Cristo",
    video: false,
    vote_average: 8.4,
    vote_count: 658,
  },
  {
    adult: false,
    backdrop_path: "/oPUOpnl3pqD8wuidjfUn17mO1yA.jpg",
    genre_ids: (5)[(16, 878, 12, 10751, 28)],
    id: 698687,
    media_type: "movie",
    original_language: "en",
    original_title: "Transformers One",
    overview:
      "The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.",
    popularity: 3303.88,
    poster_path: "/iRCgqpdVE4wyLQvGYU3ZP7pAtUc.jpg",
    release_date: "2024-09-11",
    title: "Transformers One",
    video: false,
    vote_average: 8.1,
    vote_count: 386,
  },
  {
    adult: false,
    backdrop_path: "/9oYdz5gDoIl8h67e3ccv3OHtmm2.jpg",
    genre_ids: (3)[(27, 878, 53)],
    id: 933260,
    media_type: "movie",
    original_language: "en",
    original_title: "The Substance",
    overview:
      "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
    popularity: 3173.39,
    poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
    release_date: "2024-09-07",
    title: "The Substance",
    video: false,
    vote_average: 7.3,
    vote_count: 970,
  },
  {
    adult: false,
    backdrop_path: "/v9acaWVVFdZT5yAU7J2QjwfhXyD.jpg",
    genre_ids: (3)[(16, 878, 10751)],
    id: 1184918,
    media_type: "movie",
    original_language: "en",
    original_title: "The Wild Robot",
    overview:
      "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    popularity: 8387.193,
    poster_path: "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
    release_date: "2024-09-12",
    title: "The Wild Robot",
    video: false,
    vote_average: 8.596,
    vote_count: 1817,
  },
  {
    adult: false,
    backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    genre_ids: (3)[(28, 35, 878)],
    id: 533535,
    media_type: "movie",
    original_language: "en",
    original_title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    popularity: 2493.919,
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    release_date: "2024-07-24",
    title: "Deadpool & Wolverine",
    video: false,
    vote_average: 7.712,
    vote_count: 4854,
  },
  {
    adult: false,
    backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
    genre_ids: (2)[(878, 27)],
    id: 945961,
    media_type: "movie",
    original_language: "en",
    original_title: "Alien: Romulus",
    overview:
      "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
    popularity: 3896.538,
    poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    release_date: "2024-08-13",
    title: "Alien: Romulus",
    video: false,
    vote_average: 7.279,
    vote_count: 1951,
  },
  {
    adult: false,
    backdrop_path: "/sLp1vdiIQoLgLYsOb9ebDbBYB7D.jpg",
    genre_ids: (4)[(12, 35, 14, 28)],
    id: 1091181,
    media_type: "movie",
    original_language: "fr",
    original_title: "Loups-Garous",
    overview:
      "When an old card game comes to life, a family jumps back in time to a medieval village where they must unmask werewolves to secure their return home.",
    popularity: 204.855,
    poster_path: "/nKDH9pjh1fkBcb3PNouQ0qmN6cW.jpg",
    release_date: "2024-10-22",
    title: "Family Pack",
    video: false,
    vote_average: 5.653,
    vote_count: 118,
  },
  {
    adult: false,
    backdrop_path: "/qo2jB0jejv1HTmLvoMxZOrgKsHe.jpg",
    genre_ids: (4)[(53, 9648, 18, 80)],
    id: 1148172,
    media_type: "movie",
    original_language: "hi",
    original_title: "दो पत्ती",
    overview:
      "A puzzling investigation leads a no-nonsense cop down a dark path involving the vicious rivalry between twin sisters and the volatile man they both love.",
    popularity: 119.755,
    poster_path: "/wbXSE68cDwqUPsHJcpdu7I5kSLK.jpg",
    release_date: "2024-10-24",
    title: "Do Patti",
    video: false,
    vote_average: 8,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: "/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg",
    genre_ids: (2)[(878, 28)],
    id: 335983,
    media_type: "movie",
    original_language: "en",
    original_title: "Venom",
    overview:
      "Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.",
    popularity: 1838.981,
    poster_path: "/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
    release_date: "2018-09-28",
    title: "Venom",
    video: false,
    vote_average: 6.83,
    vote_count: 15778,
  },
  {
    adult: false,
    backdrop_path: "/naNXYdBzTEb1KwOdi1RbBkM9Zv1.jpg",
    genre_ids: (2)[(27, 53)],
    id: 420634,
    media_type: "movie",
    original_language: "en",
    original_title: "Terrifier",
    overview:
      "A maniacal clown named Art terrorizes three young women on Halloween night and everyone else who stands in his way.",
    popularity: 916.876,
    poster_path: "/sFaPj5UyIAsiRuIgVl60pCYUzmR.jpg",
    release_date: "2018-01-25",
    title: "Terrifier",
    video: false,
    vote_average: 6.4,
    vote_count: 2245,
  },
  {
    adult: false,
    backdrop_path: "/cVg97LOJgrDZJ7bVmjU2KsGRYnU.jpg",
    genre_ids: (2)[(27, 9648)],
    id: 1100782,
    media_type: "movie",
    original_language: "en",
    original_title: "Smile 2",
    overview:
      "About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, Skye is forced to face her dark past to regain control of her life before it spirals out of control.",
    popularity: 766.404,
    poster_path: "/aE85MnPIsSoSs3978Noo16BRsKN.jpg",
    release_date: "2024-10-16",
    title: "Smile 2",
    video: false,
    vote_average: 6.959,
    vote_count: 197,
  },
  {
    adult: false,
    backdrop_path: "/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg",
    genre_ids: (3)[(35, 14, 27)],
    id: 917496,
    media_type: "movie",
    original_language: "en",
    original_title: "Beetlejuice Beetlejuice",
    overview:
      "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Betelgeuse, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
    popularity: 1517.536,
    poster_path: "/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg",
    release_date: "2024-09-04",
    title: "Beetlejuice Beetlejuice",
    video: false,
    vote_average: 7.196,
    vote_count: 1582,
  },
  {
    adult: false,
    backdrop_path: "/uGmYqxh8flqkudioyFtD7IJSHxK.jpg",
    genre_ids: (3)[(18, 80, 53)],
    id: 889737,
    media_type: "movie",
    original_language: "en",
    original_title: "Joker: Folie à Deux",
    overview:
      "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him.",
    popularity: 805.184,
    poster_path: "/aciP8Km0waTLXEYf5ybFK5CSUxl.jpg",
    release_date: "2024-10-01",
    title: "Joker: Folie à Deux",
    video: false,
    vote_average: 5.8,
    vote_count: 963,
  },
  {
    adult: false,
    backdrop_path: "/l0YYwVi7tIcuSGc3ssxTL5kfiHi.jpg",
    genre_ids: (2)[(53, 18)],
    id: 1364082,
    media_type: "movie",
    original_language: "en",
    original_title: "Hijack '93",
    overview:
      "In an effort to dismantle their military-backed government, four men hijack an airplane, leveraging passengers onboard in the name of social change.",
    popularity: 82.335,
    poster_path: "/nrwTBMlexcgy11MXRVRz8IZrfTI.jpg",
    release_date: "2024-10-24",
    title: "Hijack '93",
    video: false,
    vote_average: 4.7,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg",
    genre_ids: (5)[(16, 10751, 12, 35, 18)],
    id: 1022789,
    media_type: "movie",
    original_language: "en",
    original_title: "Inside Out 2",
    overview:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    popularity: 1527.121,
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    release_date: "2024-06-11",
    title: "Inside Out 2",
    video: false,
    vote_average: 7.6,
    vote_count: 4499,
  },
  {
    adult: false,
    backdrop_path: "/fNylhsI3u6NmTxeanFPDEwvT9GS.jpg",
    genre_ids: (3)[(80, 18, 53)],
    id: 835113,
    media_type: "movie",
    original_language: "en",
    original_title: "Woman of the Hour",
    overview:
      "An aspiring actress crosses paths with a prolific serial killer in '70s LA when they're cast on an episode of \"The Dating Game.\"",
    popularity: 456.339,
    poster_path: "/nc9ZqrJFbcUdlMg9lxXXtJb24jU.jpg",
    release_date: "2024-10-03",
    title: "Woman of the Hour",
    video: false,
    vote_average: 6.671,
    vote_count: 252,
  },
];
